//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VNPTPM.Model.GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do không phê duyệt cửa hàng.
        /// </summary>
        internal static string Branch_Comment {
            get {
                return ResourceManager.GetString("Branch_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách cửa hàng.
        /// </summary>
        internal static string Branch_IDList {
            get {
                return ResourceManager.GetString("Branch_IDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        internal static string Branch_Phone1 {
            get {
                return ResourceManager.GetString("Branch_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nút.
        /// </summary>
        internal static string Control_ID {
            get {
                return ResourceManager.GetString("Control_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nút.
        /// </summary>
        internal static string Control_Name {
            get {
                return ResourceManager.GetString("Control_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cửa hàng.
        /// </summary>
        internal static string Label_Branch {
            get {
                return ResourceManager.GetString("Label_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung bình luận.
        /// </summary>
        internal static string Label_Comment_Description {
            get {
                return ResourceManager.GetString("Label_Comment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File bình luận.
        /// </summary>
        internal static string Label_Comment_FileUrls {
            get {
                return ResourceManager.GetString("Label_Comment_FileUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID bình luận.
        /// </summary>
        internal static string Label_Comment_ID {
            get {
                return ResourceManager.GetString("Label_Comment_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID công việc của bình luận.
        /// </summary>
        internal static string Label_Comment_IssueID {
            get {
                return ResourceManager.GetString("Label_Comment_IssueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bình luận.
        /// </summary>
        internal static string Label_Comment_Reporter {
            get {
                return ResourceManager.GetString("Label_Comment_Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khuyến mãi.
        /// </summary>
        internal static string Label_Deal {
            get {
                return ResourceManager.GetString("Label_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon loại giảm giá.
        /// </summary>
        internal static string Label_Discount_IconUrl {
            get {
                return ResourceManager.GetString("Label_Discount_IconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại giảm giá.
        /// </summary>
        internal static string Label_Discount_ID {
            get {
                return ResourceManager.GetString("Label_Discount_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại giảm giá.
        /// </summary>
        internal static string Label_Discount_Nm {
            get {
                return ResourceManager.GetString("Label_Discount_Nm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền tài liệu.
        /// </summary>
        internal static string Label_File_AssignUnits {
            get {
                return ResourceManager.GetString("Label_File_AssignUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh.
        /// </summary>
        internal static string Label_File_Code {
            get {
                return ResourceManager.GetString("Label_File_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo tài liệu.
        /// </summary>
        internal static string Label_File_CreateAt {
            get {
                return ResourceManager.GetString("Label_File_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cờ &apos;xóa&apos;.
        /// </summary>
        internal static string Label_File_DelFlg {
            get {
                return ResourceManager.GetString("Label_File_DelFlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miêu tả tài liệu.
        /// </summary>
        internal static string Label_File_Description {
            get {
                return ResourceManager.GetString("Label_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu đính kèm.
        /// </summary>
        internal static string Label_File_FileUrls {
            get {
                return ResourceManager.GetString("Label_File_FileUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định danh tài liệu.
        /// </summary>
        internal static string Label_File_ID {
            get {
                return ResourceManager.GetString("Label_File_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ký hiệu.
        /// </summary>
        internal static string Label_File_SerialNo {
            get {
                return ResourceManager.GetString("Label_File_SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề tài liệu.
        /// </summary>
        internal static string Label_File_Title {
            get {
                return ResourceManager.GetString("Label_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật tài liệu.
        /// </summary>
        internal static string Label_File_UpdateAt {
            get {
                return ResourceManager.GetString("Label_File_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng tài liệu.
        /// </summary>
        internal static string Label_File_UserName {
            get {
                return ResourceManager.GetString("Label_File_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo log tài liệu.
        /// </summary>
        internal static string Label_FileLog_CreateAt {
            get {
                return ResourceManager.GetString("Label_FileLog_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định danh log tài liệu.
        /// </summary>
        internal static string Label_FileLog_ID {
            get {
                return ResourceManager.GetString("Label_FileLog_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng tài liệu.
        /// </summary>
        internal static string Label_FileLog_UserName {
            get {
                return ResourceManager.GetString("Label_FileLog_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Nhóm trao đổi công việc.
        /// </summary>
        internal static string Label_GroupChat_ID {
            get {
                return ResourceManager.GetString("Label_GroupChat_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên nhóm trao đổi công việc.
        /// </summary>
        internal static string Label_GroupChat_Member {
            get {
                return ResourceManager.GetString("Label_GroupChat_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm trao đổi công việc.
        /// </summary>
        internal static string Label_GroupChat_Name {
            get {
                return ResourceManager.GetString("Label_GroupChat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lễ (Dương lịch).
        /// </summary>
        internal static string Label_Holiday_Date {
            get {
                return ResourceManager.GetString("Label_Holiday_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải ngày lễ.
        /// </summary>
        internal static string Label_Holiday_Description {
            get {
                return ResourceManager.GetString("Label_Holiday_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chiu trách nhiệm chính công việc.
        /// </summary>
        internal static string Label_Issue_Assignee {
            get {
                return ResourceManager.GetString("Label_Issue_Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chuyển tiếp.
        /// </summary>
        internal static string Label_Issue_AssigneeFrom {
            get {
                return ResourceManager.GetString("Label_Issue_AssigneeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã công việc.
        /// </summary>
        internal static string Label_Issue_Code {
            get {
                return ResourceManager.GetString("Label_Issue_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả công việc.
        /// </summary>
        internal static string Label_Issue_Description {
            get {
                return ResourceManager.GetString("Label_Issue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày dự kiến kết thúc công việc.
        /// </summary>
        internal static string Label_Issue_DueDate {
            get {
                return ResourceManager.GetString("Label_Issue_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID công việc.
        /// </summary>
        internal static string Label_Issue_ID {
            get {
                return ResourceManager.GetString("Label_Issue_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã liên kết.
        /// </summary>
        internal static string Label_Issue_LinkID {
            get {
                return ResourceManager.GetString("Label_Issue_LinkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại liên kết.
        /// </summary>
        internal static string Label_Issue_LinkType {
            get {
                return ResourceManager.GetString("Label_Issue_LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link liên kết.
        /// </summary>
        internal static string Label_Issue_LinkUrl {
            get {
                return ResourceManager.GetString("Label_Issue_LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc cha.
        /// </summary>
        internal static string Label_Issue_ParentID {
            get {
                return ResourceManager.GetString("Label_Issue_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ quan trọng công việc.
        /// </summary>
        internal static string Label_Issue_Priority {
            get {
                return ResourceManager.GetString("Label_Issue_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID tiến độ công việc.
        /// </summary>
        internal static string Label_Issue_ProgressID {
            get {
                return ResourceManager.GetString("Label_Issue_ProgressID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án công việc.
        /// </summary>
        internal static string Label_Issue_ProjectID {
            get {
                return ResourceManager.GetString("Label_Issue_ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân sự liên quan công việc.
        /// </summary>
        internal static string Label_Issue_RelatedPersonel {
            get {
                return ResourceManager.GetString("Label_Issue_RelatedPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo công việc.
        /// </summary>
        internal static string Label_Issue_Reporter {
            get {
                return ResourceManager.GetString("Label_Issue_Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày dự kiến bắt đầu công việc.
        /// </summary>
        internal static string Label_Issue_StartDate {
            get {
                return ResourceManager.GetString("Label_Issue_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng công việc.
        /// </summary>
        internal static string Label_Issue_Status {
            get {
                return ResourceManager.GetString("Label_Issue_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt công việc.
        /// </summary>
        internal static string Label_Issue_Summary {
            get {
                return ResourceManager.GetString("Label_Issue_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại công việc.
        /// </summary>
        internal static string Label_Issue_TypeID {
            get {
                return ResourceManager.GetString("Label_Issue_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại công việc.
        /// </summary>
        internal static string Label_IssueType_ID {
            get {
                return ResourceManager.GetString("Label_IssueType_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại công việc.
        /// </summary>
        internal static string Label_IssueType_Name {
            get {
                return ResourceManager.GetString("Label_IssueType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả Logwork.
        /// </summary>
        internal static string Label_LogWork_Description {
            get {
                return ResourceManager.GetString("Label_LogWork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Logwork.
        /// </summary>
        internal static string Label_LogWork_ID {
            get {
                return ResourceManager.GetString("Label_LogWork_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID công việc của Logwork.
        /// </summary>
        internal static string Label_LogWork_IssueID {
            get {
                return ResourceManager.GetString("Label_LogWork_IssueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Logwork.
        /// </summary>
        internal static string Label_LogWork_LogDate {
            get {
                return ResourceManager.GetString("Label_LogWork_LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Logwork.
        /// </summary>
        internal static string Label_LogWork_Reporter {
            get {
                return ResourceManager.GetString("Label_LogWork_Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm việc.
        /// </summary>
        internal static string Label_LogWork_Worked {
            get {
                return ResourceManager.GetString("Label_LogWork_Worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trang.
        /// </summary>
        internal static string Label_obj_page {
            get {
                return ResourceManager.GetString("Label_obj_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string Label_page_ID {
            get {
                return ResourceManager.GetString("Label_page_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trang.
        /// </summary>
        internal static string Label_page_Nm {
            get {
                return ResourceManager.GetString("Label_page_Nm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chức vụ.
        /// </summary>
        internal static string Label_Part_Description {
            get {
                return ResourceManager.GetString("Label_Part_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID chức vụ.
        /// </summary>
        internal static string Label_Part_ID {
            get {
                return ResourceManager.GetString("Label_Part_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức vụ.
        /// </summary>
        internal static string Label_Part_Name {
            get {
                return ResourceManager.GetString("Label_Part_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dự án.
        /// </summary>
        internal static string Label_Project_Code {
            get {
                return ResourceManager.GetString("Label_Project_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID dự án.
        /// </summary>
        internal static string Label_Project_ID {
            get {
                return ResourceManager.GetString("Label_Project_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dự án.
        /// </summary>
        internal static string Label_Project_Name {
            get {
                return ResourceManager.GetString("Label_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo đánh giá/Duyệt xử lý xong.
        /// </summary>
        internal static string Label_Report_ApprovedComplete {
            get {
                return ResourceManager.GetString("Label_Report_ApprovedComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số việc/Hoàn thành trong tháng.
        /// </summary>
        internal static string Label_Report_CompleteinMonth {
            get {
                return ResourceManager.GetString("Label_Report_CompleteinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiếp từ tháng trước/Hết hạn.
        /// </summary>
        internal static string Label_Report_Expired {
            get {
                return ResourceManager.GetString("Label_Report_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo giao trong tháng/Hoàn thành trong tháng.
        /// </summary>
        internal static string Label_Report_LeaderinMonth {
            get {
                return ResourceManager.GetString("Label_Report_LeaderinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo giao trong tháng/Gối sang tháng khác.
        /// </summary>
        internal static string Label_Report_LeaderinNextMonth {
            get {
                return ResourceManager.GetString("Label_Report_LeaderinNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo đánh giá/Chưa xử lý xong.
        /// </summary>
        internal static string Label_Report_NotComplete {
            get {
                return ResourceManager.GetString("Label_Report_NotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo đánh giá/Chưa đánh giá.
        /// </summary>
        internal static string Label_Report_NotRating {
            get {
                return ResourceManager.GetString("Label_Report_NotRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý xong/Đúng hạn.
        /// </summary>
        internal static string Label_Report_OnTime {
            get {
                return ResourceManager.GetString("Label_Report_OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xử lý xong/Quá hạn.
        /// </summary>
        internal static string Label_Report_OutDate1 {
            get {
                return ResourceManager.GetString("Label_Report_OutDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý xong/Quá hạn.
        /// </summary>
        internal static string Label_Report_OutDate2 {
            get {
                return ResourceManager.GetString("Label_Report_OutDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xử lý xong/Còn hạn.
        /// </summary>
        internal static string Label_Report_StillValid {
            get {
                return ResourceManager.GetString("Label_Report_StillValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số việc/Tổng cộng.
        /// </summary>
        internal static string Label_Report_Sum {
            get {
                return ResourceManager.GetString("Label_Report_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số công việc quá hạn.
        /// </summary>
        internal static string Label_Report_SumOut {
            get {
                return ResourceManager.GetString("Label_Report_SumOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiếp từ tháng trước/Còn hạn.
        /// </summary>
        internal static string Label_Report_Unexpired {
            get {
                return ResourceManager.GetString("Label_Report_Unexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Nhóm người dùng.
        /// </summary>
        internal static string Label_Role_ID {
            get {
                return ResourceManager.GetString("Label_Role_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm người dùng.
        /// </summary>
        internal static string Label_Role_Name {
            get {
                return ResourceManager.GetString("Label_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Label_RolePage_PageID {
            get {
                return ResourceManager.GetString("Label_RolePage_PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        internal static string Label_RolePage_RoleID {
            get {
                return ResourceManager.GetString("Label_RolePage_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đơn vị.
        /// </summary>
        internal static string Label_Unit_ID {
            get {
                return ResourceManager.GetString("Label_Unit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo đơn vị.
        /// </summary>
        internal static string Label_Unit_Leader {
            get {
                return ResourceManager.GetString("Label_Unit_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        internal static string Label_Unit_Name {
            get {
                return ResourceManager.GetString("Label_Unit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị cha.
        /// </summary>
        internal static string Label_Unit_ParentID {
            get {
                return ResourceManager.GetString("Label_Unit_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại {0} đã bị khóa. Không thể tiếp tục đăng nhập.
        /// </summary>
        internal static string Login_AccLock {
            get {
                return ResourceManager.GetString("Login_AccLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Login_DisplayGender_F {
            get {
                return ResourceManager.GetString("Login_DisplayGender_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Login_DisplayGender_M {
            get {
                return ResourceManager.GetString("Login_DisplayGender_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Login_DisplayGender_O {
            get {
                return ResourceManager.GetString("Login_DisplayGender_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không được rỗng.
        /// </summary>
        internal static string Login_IDNotNull {
            get {
                return ResourceManager.GetString("Login_IDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} la ma xac thuc ung dung LBM.
        /// </summary>
        internal static string Login_OTPCodeContent {
            get {
                return ResourceManager.GetString("Login_OTPCodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không đúng.
        /// </summary>
        internal static string Login_OTPNotMatch {
            get {
                return ResourceManager.GetString("Login_OTPNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP không được rỗng.
        /// </summary>
        internal static string Login_OTPNotNull {
            get {
                return ResourceManager.GetString("Login_OTPNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP không được vượt quá 4 ký tự.
        /// </summary>
        internal static string Login_OTPOutOfSize {
            get {
                return ResourceManager.GetString("Login_OTPOutOfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Login_Phone {
            get {
                return ResourceManager.GetString("Login_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại tối thiểu 10 kí tự.
        /// </summary>
        internal static string Login_PhoneMinLength {
            get {
                return ResourceManager.GetString("Login_PhoneMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại không được rỗng.
        /// </summary>
        internal static string Login_PhoneNotNull {
            get {
                return ResourceManager.GetString("Login_PhoneNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập trang này!.
        /// </summary>
        internal static string MsgAccessDenined {
            get {
                return ResourceManager.GetString("MsgAccessDenined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt {0} thành công.
        /// </summary>
        internal static string MsgApproveDataSuccess {
            get {
                return ResourceManager.GetString("MsgApproveDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo dữ liệu {0} thành công!.
        /// </summary>
        internal static string MsgCreateDataSuccess {
            get {
                return ResourceManager.GetString("MsgCreateDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa {0} thành công.
        /// </summary>
        internal static string MsgDeleteDataSuccess {
            get {
                return ResourceManager.GetString("MsgDeleteDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string MsgDeleteOk {
            get {
                return ResourceManager.GetString("MsgDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu base64 không chính xác.
        /// </summary>
        internal static string MsgErrorBase64Incorrect {
            get {
                return ResourceManager.GetString("MsgErrorBase64Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự của câu trả lời &quot;{0}&quot; không tồn tại..
        /// </summary>
        internal static string MsgErrorChoiceNullOrder {
            get {
                return ResourceManager.GetString("MsgErrorChoiceNullOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời &quot;{0}&quot; và câu trả lời &quot;{1}&quot; bị trùng số thứ tự..
        /// </summary>
        internal static string MsgErrorChoiceSameOrder {
            get {
                return ResourceManager.GetString("MsgErrorChoiceSameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu của biến {0} không đúng định dạng ngày.
        /// </summary>
        internal static string MsgErrorDateWithFormat {
            get {
                return ResourceManager.GetString("MsgErrorDateWithFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại của {0}.
        /// </summary>
        internal static string MsgErrorDontInputPhone {
            get {
                return ResourceManager.GetString("MsgErrorDontInputPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn không được nhỏ hơn ngày hiện tại.
        /// </summary>
        internal static string MsgErrorDueDatetime {
            get {
                return ResourceManager.GetString("MsgErrorDueDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng tệp tin tối đa cho phép là {0} Bytes.
        /// </summary>
        internal static string MsgErrorFileUrlMaxSize {
            get {
                return ResourceManager.GetString("MsgErrorFileUrlMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình giao dịch, vui lòng liên hệ quản trị để xử lý. Chân thành xin lỗi về sự bất tiện này!.
        /// </summary>
        internal static string MsgErrorHasException {
            get {
                return ResourceManager.GetString("MsgErrorHasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gía trị của {0} không được chứa ký tự khoản trắng.
        /// </summary>
        internal static string MsgErrorHasSpace {
            get {
                return ResourceManager.GetString("MsgErrorHasSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa công việc cha &quot;{0}&quot; khi có công việc con tồn tại.
        /// </summary>
        internal static string MsgErrorHaveChildDelete {
            get {
                return ResourceManager.GetString("MsgErrorHaveChildDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID của {0} không tồn tại.
        /// </summary>
        internal static string MsgErrorIDIsNotExists {
            get {
                return ResourceManager.GetString("MsgErrorIDIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng hình ảnh tối đa cho phép là {0} MB.
        /// </summary>
        internal static string MsgErrorImageUrlMaxSize {
            get {
                return ResourceManager.GetString("MsgErrorImageUrlMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu {0} không hợp lệ.
        /// </summary>
        internal static string MsgErrorInvalidType {
            get {
                return ResourceManager.GetString("MsgErrorInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ làm việc không hợp lệ.
        /// </summary>
        internal static string MsgErrorInvalidWorkHour {
            get {
                return ResourceManager.GetString("MsgErrorInvalidWorkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Đã tồn tại trong hệ thống.
        /// </summary>
        internal static string MsgErrorIsExists {
            get {
                return ResourceManager.GetString("MsgErrorIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa loại công việc &quot;{0}&quot; vì có công việc &quot;{1}&quot; đang là loại công việc này.
        /// </summary>
        internal static string MsgErrorIssueDeleteType {
            get {
                return ResourceManager.GetString("MsgErrorIssueDeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể logwork vào ngày lớn hơn ngày hiện tại.
        /// </summary>
        internal static string MsgErrorLogDatetime {
            get {
                return ResourceManager.GetString("MsgErrorLogDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ Log Work nhiều hơn số giờ còn lại.
        /// </summary>
        internal static string MsgErrorLogHourOverLog {
            get {
                return ResourceManager.GetString("MsgErrorLogHourOverLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối đa cho phép của {0} là {1} ký tự.
        /// </summary>
        internal static string MsgErrorMaximumLength {
            get {
                return ResourceManager.GetString("MsgErrorMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối thiểu bắt buộc của {0} là {1} ký tự.
        /// </summary>
        internal static string MsgErrorMinimumLength {
            get {
                return ResourceManager.GetString("MsgErrorMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có nhiều chủ đề khảo sát đang ở trạng thái hoạt động..
        /// </summary>
        internal static string MsgErrorMultiTopic {
            get {
                return ResourceManager.GetString("MsgErrorMultiTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có chủ đề khảo sát đang ở trạng thái hoạt động..
        /// </summary>
        internal static string MsgErrorNoActiveTopic {
            get {
                return ResourceManager.GetString("MsgErrorNoActiveTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có lựa chọn trả lời trong câu hỏi &quot;{0}&quot;..
        /// </summary>
        internal static string MsgErrorNoChoice {
            get {
                return ResourceManager.GetString("MsgErrorNoChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có câu hỏi trong chủ đề khảo sát..
        /// </summary>
        internal static string MsgErrorNoQuestion {
            get {
                return ResourceManager.GetString("MsgErrorNoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy giá trị config của các {0}.
        /// </summary>
        internal static string MsgErrorNotFoundConfig {
            get {
                return ResourceManager.GetString("MsgErrorNotFoundConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn {0} không tồn tại trong hệ thống.
        /// </summary>
        internal static string MsgErrorNotFoundPath {
            get {
                return ResourceManager.GetString("MsgErrorNotFoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa chức vụ &quot;{0}&quot; vì có tài khoản &quot;{1}&quot; đang là chức vụ này.
        /// </summary>
        internal static string MsgErrorPartDeleteUser {
            get {
                return ResourceManager.GetString("MsgErrorPartDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng đang được thanh toán, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MsgErrorPaymentExisted {
            get {
                return ResourceManager.GetString("MsgErrorPaymentExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng chưa đến hạn thanh toán, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MsgErrorPaymentNotExpiry {
            get {
                return ResourceManager.GetString("MsgErrorPaymentNotExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình thanh toán, thanh toán đã bị hủy!.
        /// </summary>
        internal static string MsgErrorPaymentProcess {
            get {
                return ResourceManager.GetString("MsgErrorPaymentProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng của {0} không đúng số điện thoại.
        /// </summary>
        internal static string MsgErrorPhone {
            get {
                return ResourceManager.GetString("MsgErrorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự của câu hỏi &quot;{0}&quot; không tồn tại..
        /// </summary>
        internal static string MsgErrorQuestionNullOrder {
            get {
                return ResourceManager.GetString("MsgErrorQuestionNullOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi &quot;{0}&quot; và câu hỏi &quot;{1}&quot; bị trùng số thứ tự..
        /// </summary>
        internal static string MsgErrorQuestionSameOrder {
            get {
                return ResourceManager.GetString("MsgErrorQuestionSameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gía trị của {0} phải nằm trong khoảng {1} đến {2}.
        /// </summary>
        internal static string MsgErrorRang {
            get {
                return ResourceManager.GetString("MsgErrorRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải là số nguyên.
        /// </summary>
        internal static string MsgErrorRegularExpressionInteger {
            get {
                return ResourceManager.GetString("MsgErrorRegularExpressionInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là số.
        /// </summary>
        internal static string MsgErrorRegularExpressionNumber {
            get {
                return ResourceManager.GetString("MsgErrorRegularExpressionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị của {0} đang rỗng.
        /// </summary>
        internal static string MsgErrorRequire {
            get {
                return ResourceManager.GetString("MsgErrorRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mẫu tin cần xóa.
        /// </summary>
        internal static string MsgErrorRequiredDeleteID {
            get {
                return ResourceManager.GetString("MsgErrorRequiredDeleteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo và người nhận công việc không được trùng nhau..
        /// </summary>
        internal static string MsgErrorSamePerson {
            get {
                return ResourceManager.GetString("MsgErrorSamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tháng xem nhỏ hơn hoặc bằng tháng hiện tại.
        /// </summary>
        internal static string MsgErrorSearchMonthInvalid {
            get {
                return ResourceManager.GetString("MsgErrorSearchMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tìm kiếm (quý/năm) không hợp lệ.
        /// </summary>
        internal static string MsgErrorSearchPeriodInvalid {
            get {
                return ResourceManager.GetString("MsgErrorSearchPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chữ ký để tích hợp với hệ thống không hợp lệ.
        /// </summary>
        internal static string MsgErrorSignatureIncorrect {
            get {
                return ResourceManager.GetString("MsgErrorSignatureIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gía trị của ngày {0} phải nhỏ hơn hoặc bằng ngày {1}.
        /// </summary>
        internal static string MsgErrorStartEndDatetime {
            get {
                return ResourceManager.GetString("MsgErrorStartEndDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa đơn vị &quot;{0}&quot; vì có tài khoản &quot;{1}&quot; đang thuộc vị này.
        /// </summary>
        internal static string MsgErrorUnitDeleteUser {
            get {
                return ResourceManager.GetString("MsgErrorUnitDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa người dùng &quot;{0}&quot; vì có công việc liên quan &quot;{1}&quot;.
        /// </summary>
        internal static string MsgErrorUserDeleteIssue {
            get {
                return ResourceManager.GetString("MsgErrorUserDeleteIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa người dùng &quot;{0}&quot; vì &quot;{0}&quot; đang là lãnh đạo của đơn vị &quot;{1}&quot;.
        /// </summary>
        internal static string MsgErrorUserDeleteUnit {
            get {
                return ResourceManager.GetString("MsgErrorUserDeleteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa nhóm người dùng &quot;{0}&quot; vì có tài khoản &quot;{1}&quot; thuộc nhóm này.
        /// </summary>
        internal static string MsgErrorUserRoleDelete {
            get {
                return ResourceManager.GetString("MsgErrorUserRoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng video tối đa cho phép là {0} MB.
        /// </summary>
        internal static string MsgErrorVideoUrlMaxSize {
            get {
                return ResourceManager.GetString("MsgErrorVideoUrlMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng..
        /// </summary>
        internal static string MsgErrorWrongOldPassword {
            get {
                return ResourceManager.GetString("MsgErrorWrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lỗi {0}.
        /// </summary>
        internal static string MsgException {
            get {
                return ResourceManager.GetString("MsgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string MsgFormatDate {
            get {
                return ResourceManager.GetString("MsgFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data {0} không hợp lệ.
        /// </summary>
        internal static string MsgInValidData {
            get {
                return ResourceManager.GetString("MsgInValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khóa {0} thành công.
        /// </summary>
        internal static string MsgLockDataSuccess {
            get {
                return ResourceManager.GetString("MsgLockDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        internal static string MsgLoginFail {
            get {
                return ResourceManager.GetString("MsgLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa tạo cửa hàng hoặc cửa hàng của bạn chưa được duyệt.
        /// </summary>
        internal static string MsgNoRecordBranch {
            get {
                return ResourceManager.GetString("MsgNoRecordBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng không tồn tại.
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng cài đặt {0} không tồn tại.
        /// </summary>
        internal static string MsgNotFoundSetting {
            get {
                return ResourceManager.GetString("MsgNotFoundSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc đã được đánh giá thành công.
        /// </summary>
        internal static string MsgRatingDataSuccess {
            get {
                return ResourceManager.GetString("MsgRatingDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã từ chối phê duyệt {0} thành công.
        /// </summary>
        internal static string MsgRejectDataSuccess {
            get {
                return ResourceManager.GetString("MsgRejectDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc đã được kết thúc.
        /// </summary>
        internal static string MsgResolveDataSuccess {
            get {
                return ResourceManager.GetString("MsgResolveDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc đã được mở lại.
        /// </summary>
        internal static string MsgRestartIssueOk {
            get {
                return ResourceManager.GetString("MsgRestartIssueOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa nhóm người dùng này.
        /// </summary>
        internal static string MsgRoleDefault {
            get {
                return ResourceManager.GetString("MsgRoleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã được lưu thành công.
        /// </summary>
        internal static string MsgSaveOk {
            get {
                return ResourceManager.GetString("MsgSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        internal static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình giao dịch thành công!.
        /// </summary>
        internal static string MsgSuccessPayment {
            get {
                return ResourceManager.GetString("MsgSuccessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã mở khóa {0} thành công.
        /// </summary>
        internal static string MsgUnLockDataSuccess {
            get {
                return ResourceManager.GetString("MsgUnLockDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu {0} thành công!.
        /// </summary>
        internal static string MsgUpdateDataSuccess {
            get {
                return ResourceManager.GetString("MsgUpdateDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu tải lên thành công.
        /// </summary>
        internal static string MsgUploadOk {
            get {
                return ResourceManager.GetString("MsgUploadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Api đã bị khóa.
        /// </summary>
        internal static string MsgUserLock {
            get {
                return ResourceManager.GetString("MsgUserLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu {0} có tồn tại trong hệ thống.
        /// </summary>
        internal static string MsgValidData {
            get {
                return ResourceManager.GetString("MsgValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} trong hệ thống.
        /// </summary>
        internal static string NotFoundByName {
            get {
                return ResourceManager.GetString("NotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chủ sở hữu.
        /// </summary>
        internal static string Txt_AccountNm {
            get {
                return ResourceManager.GetString("Txt_AccountNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        internal static string Txt_Status_Approve {
            get {
                return ResourceManager.GetString("Txt_Status_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        internal static string Txt_Status_Deleted {
            get {
                return ResourceManager.GetString("Txt_Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khóa.
        /// </summary>
        internal static string Txt_Status_Locked {
            get {
                return ResourceManager.GetString("Txt_Status_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được duyệt.
        /// </summary>
        internal static string Txt_Status_Reject {
            get {
                return ResourceManager.GetString("Txt_Status_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ duyệt.
        /// </summary>
        internal static string Txt_Status_Waiting {
            get {
                return ResourceManager.GetString("Txt_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        internal static string User_Description {
            get {
                return ResourceManager.GetString("User_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string User_Part {
            get {
                return ResourceManager.GetString("User_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        internal static string User_RoleID {
            get {
                return ResourceManager.GetString("User_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        internal static string User_UnitID {
            get {
                return ResourceManager.GetString("User_UnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
    }
}
