//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AD_PAGE: ICloneable
    {
    	public AD_PAGE () {}
    
    	#region ICloneable Members
        public AD_PAGE Clone()
        {
            return (AD_PAGE)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (AD_PAGE)this.MemberwiseClone();
        }
        #endregion
        public string ID { get; set; }
        public string Name { get; set; }
        public string ParentID { get; set; }
        public Nullable<double> OrdinalNumber { get; set; }
        public Nullable<bool> MenuFlg { get; set; }
        public Nullable<bool> ButtonFlg { get; set; }
        public string Value { get; set; }
    }
}
