//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AD_ROLE_PAGE: ICloneable
    {
    	public AD_ROLE_PAGE () {}
    
    	#region ICloneable Members
        public AD_ROLE_PAGE Clone()
        {
            return (AD_ROLE_PAGE)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (AD_ROLE_PAGE)this.MemberwiseClone();
        }
        #endregion
        public string RoleID { get; set; }
        public string PageID { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> ActiveFlg { get; set; }
    }
}
