//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AD_ROLE: ICloneable
    {
    	public AD_ROLE () {}
    
    	#region ICloneable Members
        public AD_ROLE Clone()
        {
            return (AD_ROLE)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (AD_ROLE)this.MemberwiseClone();
        }
        #endregion
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> DefaultFlg { get; set; }
    }
}
