//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_ACC_LOG: ICloneable
    {
    	public DATA_ACC_LOG () {}
    
    	#region ICloneable Members
        public DATA_ACC_LOG Clone()
        {
            return (DATA_ACC_LOG)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_ACC_LOG)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public string Phone { get; set; }
        public string OTPCode { get; set; }
        public Nullable<System.DateTime> SigninAt { get; set; }
        public Nullable<System.DateTime> SignoutAt { get; set; }
        public string IMEICode { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
