//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_NOTIFY_SEEN: ICloneable
    {
    	public DATA_NOTIFY_SEEN () {}
    
    	#region ICloneable Members
        public DATA_NOTIFY_SEEN Clone()
        {
            return (DATA_NOTIFY_SEEN)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_NOTIFY_SEEN)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> NotifyID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> SeenFlg { get; set; }
        public Nullable<System.DateTime> SeenAt { get; set; }
    }
}
