//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_PROCESS: ICloneable
    {
    	public DATA_PROCESS () {}
    
    	#region ICloneable Members
        public DATA_PROCESS Clone()
        {
            return (DATA_PROCESS)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_PROCESS)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MeetingID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ActiveFlg { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    }
}
