//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_QUESTION: ICloneable
    {
    	public DATA_QUESTION () {}
    
    	#region ICloneable Members
        public DATA_QUESTION Clone()
        {
            return (DATA_QUESTION)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_QUESTION)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> GroupID { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public Nullable<bool> EndFlg { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    }
}
