//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_MEMBER: ICloneable
    {
    	public DATA_MEMBER () {}
    
    	#region ICloneable Members
        public DATA_MEMBER Clone()
        {
            return (DATA_MEMBER)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_MEMBER)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MeetingID { get; set; }
        public string UserName { get; set; }
        public string SeatPosition { get; set; }
        public string QRCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public string InviteBy { get; set; }
        public string Note { get; set; }
        public Nullable<bool> ApproveFlg { get; set; }
        public Nullable<bool> CheckedFlg { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    }
}
