//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_DOCUMENT: ICloneable
    {
    	public DATA_DOCUMENT () {}
    
    	#region ICloneable Members
        public DATA_DOCUMENT Clone()
        {
            return (DATA_DOCUMENT)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_DOCUMENT)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MeetingID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<bool> DownloadFlg { get; set; }
        public Nullable<bool> PublicFlg { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    }
}
