//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_UNIT: ICloneable
    {
    	public M_UNIT () {}
    
    	#region ICloneable Members
        public M_UNIT Clone()
        {
            return (M_UNIT)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (M_UNIT)this.MemberwiseClone();
        }
        #endregion
        public string ID { get; set; }
        public string Name { get; set; }
        public string ParentID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<bool> DelFlg { get; set; }
        public string Leader { get; set; }
    }
}
