//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPTPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class sysdiagram: ICloneable
    {
    	public sysdiagram () {}
    
    	#region ICloneable Members
        public sysdiagram Clone()
        {
            return (sysdiagram)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (sysdiagram)this.MemberwiseClone();
        }
        #endregion
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
